project:
  type: website
  output-dir: docs

website:
  title: "Justice Hub"
  search:
    type: textbox
  
  navbar:
    background: light
    logo: jh-docs.png
    logo-alt: "JusticeHub logo."
    title: false
    collapse-below: lg
    search: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Guide"
        href: page/guide/index.qmd
      - text: "Datasets"
        href: page/datasets/index.qmd
      - text: "Learn"
        href: page/learn/index.qmd
      - text: "Collaborate"
        href: page/collaborate/index.qmd
      - text: "FAQ"
        href: page/faq/index.qmd
      - text: "Resources"
        href: page/resources/index.qmd
        
  sidebar: 
    - title: "Guide"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - page/guide/index.qmd
        - section: "Explore Datasets"
          contents:
            - page/guide/explore/searchDatasets.qmd
            - page/guide/explore/datasetCategories.qmd
        - section: "Contribute Datasets"
          contents:
            - page/guide/contributeDatasets.qmd
   
    - title: "Datasets"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - page/datasets/index.qmd
        - "---"
        - section: "Budgets for Justice"
          contents:
            - page/datasets/budgets/index.qmd
            - section: "Case Studies"
              contents:
                - page/datasets/budgets/case-studies/prison.qmd
                - page/datasets/budgets/case-studies/police.qmd
                - page/datasets/budgets/case-studies/justice.qmd
        - "---"
        
  page-footer:
    left: |
      Maintained by
      [![](https://github.com/CivicDataLab/civicdatalab.github.io/raw/master/static/cdl_logo.png){fig-alt="RStudio" width=45px}](https://civicdatalab.in/)
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com/JusticeHubIndia
        aria-label: JusticeHub Twitter
      - icon: github
        href: https://github.com/justicehub-in/justicehub
        aria-label: JusticeHub GitHub
      - icon: newspaper
        href: https://dataforjustice.substack.com/
        aria-label: Data for Justice Newsletter
      - icon: rss
        href: https://justicehub.in
        aria-label: JusticeHub Docs RSS

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual